version: "3.1"

volumes:
  acme-webroot:
    driver: local
  certificates:
    driver: local

secrets:
  certbot.domains:
    file: ./certbot.domains

services:
  certbot:
    image: fentas/certbot:latest
    environment:
      - CERTBOT_DOMAINS=/run/secrets/certbot.domains
      - LE_STAGING=1
      - LE_CRON_TIME='@daily'
      - LE_RSA_KEY_SIZE=2048
      - LE_EMAIL='replace.me@example.com'
    volumes:
      - acme-webroot:/var/acme-webroot
      - certificates
    secrets:
      - certbot.domains
