version: "3.1"

volumes:
  acme-webroot:
    driver: local
  certificates:
    driver: local

secrets:
  certbot.domains:
    file: ./certbot.domains

services:
  certbot:
    image: fentas/certbot:latest
    environment:
      - CERTBOT_DOMAINS=/var/secrets/certbot.domains
      - LETSENCRYPT_STAGING=0
      - LETSENCRYPT_CRON_TIME='@daily'
      - LETSENCRYPT_RSA_KEY_SIZE=2048
      - LETSENCRYPT_EMAIL='replace.me@example.com'
    volumes:
      - acme-webroot:/var/acme-webroot
      - certificates
